sde1000/python-dali

.gitignore
CHANGES.rst
dali/driver/base.py
dali/driver/hasseb.py
dali/driver/tridonic.py
dali/interface.py
debian/changelog
setup.py

Implements #23.
This PR adds ``dali.driver.base``, which contains general contracts how to implement synchronous and asynchronous DALI drivers and USB backend implementation.
Further it adds a concrete driver implementation for Tridonic DALI USB device. It basically works, but needs more testing and finalization.

Driver overhaul - Add a general contract for writing various drivers for communication

---

dali/driver/tridonic.py

Using subscript notation on struct seems to return the byte value as
an int on python 3, causing struct.unpack to raise. Switching
to unpack_from should preserve backwards compatibility.
Closes #49

Fix unpacking seqnum in tridonic async send

---

dali/driver/hasseb.py

Finally got sometime to upgrade my setup with Hasseb controller.
The driver has these orphan imports
Also of note:
- It requires pyhidapi
From a previous PR from @hasseb :
"To install pyhidapi:  
git clone https://github.com/awelkie/pyhidapi.git  
cd pyhidapi  
sudo python3 setup.py install"
This is important as this library is not available as a pip package... can we replace this by something more standard @hasseb ?

Cleaning Hasseb driver

---

examples/50-dali-hid.rules

Enhances the _udev_ rules:
* In addition to physical connection, allows support of logical _udev_ triggering using `udevadm` command,
* Does not remove any previously created symbolic link for the device anymore.

Udev rules

---

dali/driver/hid.py

This fixes two bugs that I spotted while working with the Tridonic driver:
- ```asyncio.wait_for()``` was called in ```tridonic._bus_watch()``` without handling the ```TimeoutError```
- ```tridonic._outstanding``` dictionary was not being reset correctly in ```tridonic._shutdown_device()```

Fix two small bugs in the asyncio Tridonic driver.

---

dali/driver/hasseb.py

Added a sequence runner to the Hasseb master. Implementation proposed by @sde1000 in https://github.com/sde1000/python-dali/issues/88, tested with sequences `Commissioning`, `QueryDeviceTypes`, `SetGroups`, and `QueryGroups`.

Add sequence runner to Hasseb master

---

dali/tests/fakes.py
dali/tests/test_fakes.py

This feature branch adds the necessary message handling to fakes.py to
handle the various DALI level control messages, e.g. DAPC,
RecallMaxLevel, etc. Such a feature was found to be helpful when
testing out higher level code which uses this library, by enabling the
use of fake DALI devices which correctly respond to certain messages.
Perhaps this isn’t the ideal place for such code to live, but since
fakes.py already implemented the majority of the necessary features
this seems to be the best fit within the existing structure.
Tests have been added to cover all of the additional code.

Add "level" support to fakes.py

---

.github/workflows/run-tests.yml
README.rst
dali/command.py
dali/driver/serial.py
dali/driver/trace_logging.py
dali/tests/fakes_serial.py
dali/tests/test_dummy.py
examples/async-serial-luba.py
pytest.ini

Lunatone make a series of DALI interface devices which communicate with a host over RS232 serial, using a protocol [defined by Lunatone](https://www.lunatone.com/wp-content/uploads/2021/04/LUBA_Protocol_EN.pdf) called 'LUBA'.
This pull request adds support into `python-dali` for LUBA interface devices, as briefly discussed in #102. The driver API largely follows the existing `hid` classes of drivers, including drop-in compatible support for sequences.

Add Lunatone LUBA RS232 driver

---

.github/workflows/run-tests.yml
README.rst
dali/address.py
dali/command.py
dali/device/__init__.py
dali/device/general.py
dali/device/helpers.py
dali/device/pushbutton.py
dali/device/sequences.py
dali/driver/serial.py
dali/gear/general.py
dali/memory/location.py
dali/tests/fakes.py
dali/tests/fakes_serial.py
dali/tests/test_command.py
dali/tests/test_device_sequences.py
dali/tests/test_dummy.py
dali/tests/test_events.py
dali/tests/test_fakes.py
dali/tests/test_memory.py
examples/async-serial-luba.py

IEC 62386 part 103 defines "event" messages, which can be sent by control devices to indicate various inputs or changes. This commit introduces support for encoding and decoding these messages, as well as a handful of new sequences for making it easier to work with them.
Support has been added for IEC 62386 part 301 "push button" devices, further device types should be simple enough to add in later. Unsupported types will be safely ignored by the library.

Add support for DALI 24-bit event messages

---

README.rst
dali/gear/__init__.py
dali/gear/colour.py
dali/gear/sequences.py
dali/tests/fakes.py
dali/tests/fakes_serial.py
dali/tests/test_colour.py
dali/tests/test_dummy.py
dali/tests/test_fakes.py
examples/async-serial-luba.py

Based on [a fork I'd found](https://github.com/sde1000/python-dali/compare/master...petrilgner:python-dali:master) by [Petr Ilgner](https://github.com/petrilgner/) I've added support for IEC 62386-208 DALI-2 DT8 colour temperature control gear. I've kept his original commits by cherry-picking them, so that the correct attribution remains in the commit history.
As well as the `dali.gear.colour` module, there's a new `dali.gear.sequences` module, which contains `SetDT8ColourValueTc()` and `QueryDT8ColourValue()` sequences.
I only have access to colour temperature gear, so support isn't completed for other types (e.g. RGBWAF, x-y coordinate). These should be easy enough to add in by someone who has such hardware to test with. All command opcodes have been implemented, even though I am not …

Add DALI DT8 colour gear support

---

dali/device/general.py
dali/device/sequences.py
dali/tests/test_device_sequences.py

I realised my implementation of the event filters could be slightly improved – the `InstanceEventFilter` enum is an `IntEnum`, so it makes sense for the `SetEventFilters` sequence to be able to handle using a plain `int` as well as the proper enum type. This mostly is useful for the higher-level application code I'm writing, by allowing it to be able to run `SetEventFilters` with `filter_value=0` to disable all filters regardless of type (assuming that the filters are only 8 bits wide, which is so far the case for all types I've seen).

Fix event filter type handling for control devices

---

dali/device/helpers.py
dali/device/light.py
dali/tests/test_events.py
examples/async-serial-luba.py

Related to #108, I've now also got support for Light Sensor devices.
This one was pretty straightforward, there's just one event type, which contains a 10-bit encoded integer of relative illuminance. To go along with it there's a handful of settings, similar to other input devices.

 Add support for DALI Light Sensor devices 

---

dali/device/__init__.py

Without importing these modules explicitly, the `examples/async-buswatch.py` would just report back stuff like `UnknownEvent(short_address=43, data=11)`. Rather than letting all consumers import everything, let's follow the pattern set forth by the `pushbutton.py`, and import other decoders as well.
Fixes: e79e39d Add support for DALI Occupancy Sensor devices
Fixes: f0a0755 Add support for DALI Light Sensor devices

Parse events from movement and light sensors by default

---

dali/gear/colour.py
dali/gear/general.py
dali/gear/sequences.py
examples/async-tc.py

I have a bunch of DT8 Osram OTi DALI DT6/8 devices which are by default set to something like 2700-6400K, but my LED strips have a different CT. Lunatone's SW won't allow me to change the *physical* Tc limits, so let's write a script which assists with this configuration.
Also some unrelated bugfixes as standalone commits.
Without this patch, dumping DALI traffic would show stuff like this:
```
QueryDeviceType(<address (control gear) 0>) -> multiple
QueryNextDeviceType(<address (control gear) 0>) -> LED lamp
QueryNextDeviceType(<address (control gear) 0>) -> BackwardFrame(8)
QueryNextDeviceType(<address (control gear) 0>) -> none / end
```
This is as per 62386-209:2011, section 11.3.4.2, "Application extended configuration commands".
Fixes: b706666 Expand DT8 support with tests and …

DT8: support setting Tc limits, and other improvements

---

dali/gear/led.py

- led: better printing of Part 207's Fast Fade Time
- led: one more bit for OPERATING MODE
My copy of 62386-207:2009 says that command 252 (“QUERY OPERATING MODE”) also has bit#4 defined as "non-logarithmic dimming curve active".

two improvements for the `led` module

---

dali/driver/hid.py

I have more than one control device, which is why the `examples/async-dalitest.py` hits a framing error when checking if there are any control devices connected. When the bus_watch feature is enabled, this hit a Python error due to some incomplete rename/refactoring where this single occurrence was not changed by mistake.
Fixes: c72374c ("Update the async Tridonic DALI-USB driver to work with 24-bit frames")

tridonic: Fix bus traffic dumping

---

dali/driver/hid.py

That's the endless joy of languages with no compile-time variable lookup.
Fixes: ea01ab3 ("asyncio-based drivers for USB devices that present as HID")

hid: fix wrong variable name

---

dali/driver/hid.py

~~I have no idea if this actually reaches the physical DALI bus, but~~ I've checked that the bus watcher picks up the traffic. So, this can be already used to persuade some real code that's connected to the real DALI bus that a sensor "sent us something".
I have some internal code that switches my DALI lights on and off based on a DALI movement sensor. With this patch in place, I can simulate this movement, and my light went on, as if someone really walked in our hallway:
```python
from dali.device.occupancy import OccupancyEvent
x = OccupancyEvent(short_address=45, instance_number=0,
data=OccupancyEvent.EventData(movement=True, occupied=True))
await dev.send(x)
```
Caveat: the usual bits about addressing of event messages apply (I tried to write this up at [electronics …

tridonic: support sending 8-bit backward frames

---

README.rst
dali/driver/atxled.py
examples/sync-dalihat.py

This uses the Raspberry PI on-board serial port to communicate at 19200 baud to the Dali Hat,
the hardware on the hat adapts the UART serial data stream into DALI encoding.
This uses pyserial to read from the dali hat device and implements a sync driver.
An example using the Dali Hat driver is included, and an entry is added to the README file.

    Add driver for Atx Led Dali Hat (AL-DALI-HAT).

---

dali/device/sequences.py
dali/tests/test_device_sequences.py
examples/async-dalitest.py

The standard (62386-103:2014, chapter 9.7) states that the "resolution" of an instance is not always 8-bits. If it's any longer, a proper read involves a transaction and a sequence of commands. If the number is not divisible by 8, extra trailing bits have to be truncated.
Tested on Lunatone DALI-2 MC (`86459532-2`) and Lunatone CS-2 (`86458670`). The push button coupler is a part-301 device where the standard says that the on-the-wire values are either `0x00` or `0xff`, but the actual resolution (and therefore the correct numeric value) is either 0 or 1. The other device, a combined movement sensor with a light meter, supports 11 bits of resolution for the lux meter and therefore it requires a `"QUERY INPUT VALUE"` followed by a `"QUERY INPUT VALUE LATCH"` and dropping the extra 5 bits.

Control Devices: respect "resolution" when reading "inputValue"

---

dali/device/helpers.py
dali/tests/test_device_sequences.py

I have a bunch of non-pushbutton switches connected to some of my Lunatone DALI-2 MC pushbutton couplers. These devices unfortunately set the `"inputDeviceError"` bit whenever any of its inputs is closed/shorted for longer than `T_stuck`.
The 62386-301:2017 says (Table 4, page 15) that this timer is up to 255s, which is definitely not enough for a door sensor. The same standard then says that such errors should be propagated to bit 0 in the `"instanceErrorByte"`, which python-dali does not query. However, my devices unfortunately also propagate this status into the `"inputDeviceError"`, and that means that the initial discovery of instance numbers to instance types won't recognize these buttons at all.
I was not able to find a reference in the standard whether any `"instanceError"` …

DeviceInstanceMapper: do not skip devices with inputDeviceError

---

dali/driver/serial.py

New hardware with some updates to protocol.
LUBA protocol:
https://www.lunatone.com/wp-content/uploads/2021/04/LUBA_Protocol_EN.pdf
DALI-2 USB device shows up as `/dev/ttyACM0` instead of previous `ttyUSB0`.
In datasheet rev 1.1 they added USB device support which features switchable power supply.
There's also small change in the `0x80` / `0x81` in rev 1.4...
As I don't have other devices, I'm unable to check for backwards compatibility, therefore this PR is marked as RFC...

RFC: Add support for Lunatone DALI-2 USB dongle

---

dali/gear/sequences.py

I was wondering why the code was sending a seemingly useless command, but it turns out that this is explicitly mandated by a note in the standard. Let's put that into a comment.

DT8: clarify why "QUERY ACTUAL LEVEL" is needed

---

README.rst
dali/gear/__init__.py
dali/gear/converter.py
examples/async-dalitest.py

Tested with Lunatone 86458508-AN. This one only appears to support switching between linear and logarithmic dimming curves, and some (undocumented) manufacturer's extensions. Support for pullup handling as well as switching between the 0-10V and 1-10V ranges is not there.

Add support for DT5 (0-10V conversion) devices

---

dali/driver/hid.py

Two related commits:
These were all logged as debug messages, which means that they are not shown by default. This makes any debugging of failures much harder, see, e.g., #124.
I was playing with some commands, and one of my devices apparently just won't send any reply to a DT5 `ResetConverterSettings`. That's a `sendtwice=True` command, and when that happens, I was getting an assertion failure later on on line 600, which looks pretty much like bug #124:
```
15:00:59.333780 D: tridonic: Sending with seq e7
15:00:59.339550 D: tridonic: waiting for outstanding_transmissions=1 {response=}
15:00:59.357560 D: tridonic: _handle_read 12730000C105FFFFE7
15:00:59.363037 D: tridonic: bus_watch message 12730000C105FFFFE7
15:00:59.368941 D: tridonic: Command EnableDeviceType(5), immediate …
```

tridonic: fix AssertionFailure
